name: Deploy AE Website

on:
  push:
    branches:
      - main  

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up SSH key
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_ed25519
        chmod 600 ~/.ssh/id_ed25519
        ssh-keyscan 35.242.181.156 >> ~/.ssh/known_hosts

    - name: Execute deployment script via SSH
      run: |
        ssh -i ~/.ssh/id_ed25519 -o StrictHostKeyChecking=no frontend@35.242.181.156 << 'EOF'
          cd /ae-website
          git pull origin main
          sudo systemctl restart nginx
        EOF
